/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AdminPage': RouteRecordInfo<'/AdminPage', '/AdminPage', Record<never, never>, Record<never, never>>,
    '/FriendPage': RouteRecordInfo<'/FriendPage', '/FriendPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/LoginPage': RouteRecordInfo<'/LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/LogPage': RouteRecordInfo<'/LogPage', '/LogPage', Record<never, never>, Record<never, never>>,
    '/NavBar': RouteRecordInfo<'/NavBar', '/NavBar', Record<never, never>, Record<never, never>>,
    '/ProfileView': RouteRecordInfo<'/ProfileView', '/ProfileView', Record<never, never>, Record<never, never>>,
    '/RegisterPage': RouteRecordInfo<'/RegisterPage', '/RegisterPage', Record<never, never>, Record<never, never>>,
  }
}
